name: Turbocache Action
description: "A GitHub Action to integrate Turbocache into your workflow"
branding:
  icon: "fast-forward"
  color: "red"
author: Turbocache
inputs: {}
runs:
  using: "node16"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
